Allow custom options; Bump version (v1.0.0)
AlexanderMoskovkin/saucelabs-connector pull request #33
Opened 2019-07-29 16:21 UTC by AndreyBelym

2019-08-20 13:01 UTC, AndreyBelym commented
\cc @miherlosev

2019-08-20 13:36 UTC, AndreyBelym commented
\cc @kirovboris

2019-08-20 15:09 UTC, miherlosev requested changes

2019-08-20 15:09 UTC, miherlosev commented on src/index.js
> +    return new Promise((resolve, reject) => {
You can promisify the `sauceConnectLauncher` too.
```js
const promisifiedSauceConnectLauncher = promisify('sauceConnectLauncher');

function createSauceConnectProcess (options) {
   return promisifiedSauceConnectLauncher(options);
}
```

2019-08-20 15:09 UTC, miherlosev commented on src/index.js
> +        return JSON.parse(response.body).concurrency[this.username].remaining.overall;
I propose to handle connection errors for all request and display clear messages for them.

2019-08-20 15:09 UTC, miherlosev commented on .eslintrc
> +    "keyword-spacing": 2,
Add `no-var` rule.

2019-08-20 15:09 UTC, miherlosev commented on src/index.js
> +        if (browser.browserName.toLowerCase() === 'internet explorer' && /11(\.\d*)?$/.test(browser.version)) {
Move this condition to the util function.

2019-08-20 15:09 UTC, miherlosev commented on src/index.js
> +import { promisify } from 'util';
Will we use Typescript here?

2019-08-20 15:09 UTC, miherlosev commented on src/sauce-storage.js
> +        var buffer = await readFile(`${filePath}${fileName}`);
Need to handle non-existing file.

2019-08-21 08:13 UTC, kirovboris requested changes
/r-

2019-08-21 08:13 UTC, kirovboris commented on package.json
> +  "contributors": [
No offense, since we in the dx repo 😃 :
```js
"author": {
    "name": "Developer Express Inc.",
    "url": "https://www.devexpress.com/"
}
```

2019-08-21 08:13 UTC, kirovboris commented on src/index.js
> +import { promisify } from 'util';
It's not necessary for this repo, because there aren't a lot code here, but if You want, You're welcome.

2019-08-21 08:13 UTC, kirovboris commented on src/index.js
> +
Please remove the extra line

2019-08-21 08:13 UTC, kirovboris commented on src/index.js
> +    async connect () {
Please add an empty line

2019-08-21 08:13 UTC, kirovboris commented on src/index.js
> +        while (attempts < maxAttemptCount) {
```while (attempts++ < maxAttemptCount) {```

2019-08-21 08:13 UTC, kirovboris commented on src/index.js
> +        jobOptions = { ...jobOptions, ...browser };
[minor/recommendation] This method huge and not readable, it'd be nice to simplify it.

2019-08-21 08:13 UTC, kirovboris commented on src/index.js
> +        var initParams = {
`no-var`

2019-08-21 08:13 UTC, kirovboris commented on src/index.js
> +        var webDriver = wd.promiseChainRemote(`ondemand.${SAUCE_API_HOST}`, 80, this.username, this.accessKey);
`80`? It's the `SAUCE_LAB_PORT` I suppose

2019-08-21 08:13 UTC, kirovboris commented on src/index.js
> +        if (browser.browserName.toLowerCase() === 'internet explorer' && /11(\.\d*)?$/.test(browser.version)) {
[minor/recommendation]
It'd be nice to keep in constants (except test files of course):
1. all regular expression,
2. all number except `-1,0,1`,
3. all strings and templates, if it's possible

Also I'm sure there's some eslint plugin which may help.

2019-12-02 06:55 UTC, kirovboris approved these changes

2020-01-16 18:56 UTC, tonyzilla commented
@AndreyBelym we are interested in these changes too, where are we at with the rework?

2020-07-08 21:41 UTC, gbruins commented
This change will allow me to use saucelabs-connector on our production build server, on which we have a shared sauce connect tunnel.   Looks like it's been approved and has no conflicts.   Can it be integrated?

2020-07-09 11:12 UTC, AndreyBelym commented
It's only partially approved, I still need to fix a lot of things.

2020-09-09 20:40 UTC, gbruins commented
@AndreyBelym Sorry to bug, but do you intend to address this anytime soon?

2020-09-09 20:42 UTC, AndreyBelym commented
Yep, I will try to finish it after finishing other tasks

2021-01-08 19:18 UTC, gbruins commented
@AndreyBelym - do you still plan to address this issue?

2021-01-12 06:15 UTC, AndreyBelym commented
Yes, I still have plans to finish it, but currently there is no progress.

2021-03-30 08:41 UTC, miherlosev approved these changes

2021-03-30 14:21 UTC, AndreyBelym reviewed
LGTM, all thanks to @Farfurix 👍

2021-03-31 09:28 UTC, DIRECTcut approved these changes

2021-03-31 10:10 UTC, merged